// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9ZporSf307guXcNkS-z0MrSsWY1FxxU',
    appId: '1:660659680309:web:26cfd910af0002a7a6ed7c',
    messagingSenderId: '660659680309',
    projectId: 'farmers-weather-app-ecba5',
    authDomain: 'farmers-weather-app-ecba5.firebaseapp.com',
    storageBucket: 'farmers-weather-app-ecba5.firebasestorage.app',
    measurementId: 'G-3M55TC9JKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDihnJ5nklRAaWIa1us7mZZdh6Jfj4pNNQ',
    appId: '1:660659680309:android:c82e90837049b5dda6ed7c',
    messagingSenderId: '660659680309',
    projectId: 'farmers-weather-app-ecba5',
    storageBucket: 'farmers-weather-app-ecba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0q1t4jG3jTpmpoJOiBXXxAEC8oufFZ4',
    appId: '1:660659680309:ios:7e7c76afab035858a6ed7c',
    messagingSenderId: '660659680309',
    projectId: 'farmers-weather-app-ecba5',
    storageBucket: 'farmers-weather-app-ecba5.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0q1t4jG3jTpmpoJOiBXXxAEC8oufFZ4',
    appId: '1:660659680309:ios:7e7c76afab035858a6ed7c',
    messagingSenderId: '660659680309',
    projectId: 'farmers-weather-app-ecba5',
    storageBucket: 'farmers-weather-app-ecba5.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG9ZporSf307guXcNkS-z0MrSsWY1FxxU',
    appId: '1:660659680309:web:83a1544a769182e2a6ed7c',
    messagingSenderId: '660659680309',
    projectId: 'farmers-weather-app-ecba5',
    authDomain: 'farmers-weather-app-ecba5.firebaseapp.com',
    storageBucket: 'farmers-weather-app-ecba5.firebasestorage.app',
    measurementId: 'G-YVMV1E0QQS',
  );
}
